name: $(Build.SourceBranchName)-$(Date:yyyyMMdd)-$(Rev:.r)
trigger:
- main
pool:
  vmImage: 'windows-latest'

jobs:
- job: Terraform_ACR_Creation
  displayName: 'Terraform ACR Creation'
  steps:
    - checkout: self
    - task: