apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: backend-namespace
type: Opaque
data:
  jwt-secret: N2Y1Y2ZmMmRkYWY4NjExYWY2OGI4MDVjNTliM2M1ZWExNzZlNGYxMGFlOTY0YWVmNTZjYjc5NWY3OGNjMTllNw==


# JWT_SECRET is a secret key used to sign and verify JSON Web Tokens (JWTs) in your backend application.
# It is very important for authentication and security in apps built with Node.js + Express + MongoDB 🔐
# run cvommand to generate run: node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
# convert it to base 64 and update here