#Run below command before running the script
#az extension add --name azure-devops
#az devops configure --defaults organization=https://dev.azure.com/<your-org> project=<your-project>


# Variables
$resourceGroup = "chatapp-resources"
$location = "eastus"
$storageAccount = "chatappresources1"
$containerName = "terraform"

$serviceConnectionName = "chatapp"

# Get subscription info
$subscriptionId = az account show --query id -o tsv
$subscriptionName = az account show --query name -o tsv

Write-Host "Using subscription: $subscriptionName ($subscriptionId)"

# 1. Create Resource Group
az group create `
  --name $resourceGroup `
  --location $location

# 2. Create Storage Account
az storage account create `
  --name $storageAccount `
  --resource-group $resourceGroup `
  --location $location `
  --sku Standard_LRS

az storage container create `
  --name $containerName `
  --account-name $storageAccount `
  --account-key $storageKey

# 4. Create App Registration (App + Service Principal) for service connection
$appName = "chatapp-sp"

# Remove existing app/service principal if present
$existingApp = az ad app list --display-name $appName --query '[0]' -o json | ConvertFrom-Json
if ($existingApp) {
  $existingAppId = $existingApp.appId
  Write-Host "Found existing App Registration: $existingAppId. Deleting existing service principal and app."
  az ad sp delete --id $existingAppId 2>$null || Write-Host "No existing service principal to delete."
  az ad app delete --id $existingAppId 2>$null || Write-Host "No existing app to delete."
}

# Create App Registration
$app = az ad app create --display-name $appName --identifier-uris "api://$appName" -o json | ConvertFrom-Json
$appId = $app.appId

# Create Service Principal for the App
az ad sp create --id $appId

# Tenant id
$tenant = az account show --query tenantId -o tsv

Write-Host "App Registration and Service Principal created: $appId"

# 5. Create Azure DevOps Service Connection (Workload Identity Federation — no secret)
$serviceEndpoint = @{
  name = $serviceConnectionName
  type = "azurerm"
  authorization = @{
    scheme = "WorkloadIdentityFederation"
    parameters = @{
      tenantid          = $tenant
      serviceprincipalid = $appId
    }
  }
  data = @{
    subscriptionId   = $subscriptionId
    subscriptionName = $subscriptionName
    environment      = "AzureCloud"
    scopeLevel       = "Subscription"
  }
} | ConvertTo-Json -Depth 10

$endpointFile = "service-endpoint.json"
$serviceEndpoint | Out-File -FilePath $endpointFile -Encoding utf8

az devops service-endpoint create --service-endpoint-configuration $endpointFile

Write-Host "Service connection created: $serviceConnectionName"

# 6. Retrieve the federation subject and issuer generated by Azure DevOps
$endpoint = az devops service-endpoint list `
  --query "[?name=='$serviceConnectionName'] | [0]" -o json | ConvertFrom-Json
$endpointId = $endpoint.id

$endpointDetails = az devops service-endpoint show --id $endpointId -o json | ConvertFrom-Json
$federationSubject = $endpointDetails.authorization.parameters.workloadIdentityFederationSubject
$federationIssuer  = $endpointDetails.authorization.parameters.workloadIdentityFederationIssuer

Write-Host "Federation Issuer : $federationIssuer"
Write-Host "Federation Subject: $federationSubject"

# 7. Bind the federated credential to the App Registration
$federatedCredential = @{
  name      = "azuredevops-$serviceConnectionName"
  issuer    = $federationIssuer
  subject   = $federationSubject
  audiences = @("api://AzureADTokenExchange")
} | ConvertTo-Json

$fedCredFile = "federated-credential.json"
$federatedCredential | Out-File -FilePath $fedCredFile -Encoding utf8

az ad app federated-credential create --id $appId --parameters $fedCredFile

Write-Host "Federated credential bound to App Registration: $appId"

# 8. Assign Roles to the Service Principal
az role assignment create `
  --assignee $appId `
  --role Contributor `
  --scope /subscriptions/$subscriptionId/resourceGroups/$resourceGroup

Write-Host "Contributor role assigned on RG to: $appId"

az role assignment create `
  --assignee $appId `
  --role "User Access Administrator" `
  --scope /subscriptions/$subscriptionId/resourceGroups/$resourceGroup

Write-Host "User Access Administrator role assigned on RG to: $appId"