apiVersion: v1
kind: Service
metadata:
  name: mongodb-clusterip-service
  labels:
    app: DB
  namespace: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: DB