apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-headless
  namespace: mongodb
  labels:
    app: DB
spec:
  clusterIP: None
  selector:
    app: DB
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017


#The headless service is what gives each MongoDB pod its own stable DNS identity, 
#which is required for replica set membership, leader election, and pod-to-pod replication to work correctly.