apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-azure-disk
  labels:
    app: DB
spec:
  storageClassName: managed-standard-retain-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  
