apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azure-disk
  labels:
    app: DB
  namespace: mongodb
spec:
  storageClassName: managed-standard-retain-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi